#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const projectRoot = path.resolve(__dirname, "..");
const configPath = path.join(projectRoot, "board-config.json");
const outputPath = path.join(projectRoot, "src", "BoardData.idr");

const statusConstructors = new Set(["Todo", "InProgress", "Done"]);

function escapeIdrisString(value) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
}

function loadConfig() {
  const raw = fs.readFileSync(configPath, "utf8");
  return JSON.parse(raw);
}

function validateTasks(tasks) {
  if (!Array.isArray(tasks) || tasks.length === 0) {
    throw new Error("tasks must be a non-empty array");
  }
  return tasks.map((task, index) => {
    if (typeof task.id !== "number") {
      throw new Error(`Task at index ${index} is missing numeric id`);
    }
    if (typeof task.description !== "string" || task.description.length === 0) {
      throw new Error(`Task #${task.id} must have a description`);
    }
    if (!statusConstructors.has(task.status)) {
      throw new Error(
        `Task #${task.id} has invalid status ${task.status}. Use Todo, InProgress, or Done.`
      );
    }
    return {
      id: task.id,
      description: escapeIdrisString(task.description),
      status: task.status,
    };
  });
}

function generateModule(tasks) {
  const taskLines = tasks
    .map(
      (task) =>
        `    MkTask ${task.id} "${task.description}" ${task.status}`
    )
    .join("\n    , ");
  return `||| This module is auto-generated by scripts/generate-board.js
module BoardData

import TaskTypes

public export
board : TaskBoard
board =
  MkBoard
    [ ${taskLines}
    ]
`;
}

function main() {
  const config = loadConfig();
  const tasks = validateTasks(config.tasks);
  const moduleSource = generateModule(tasks);
  fs.writeFileSync(outputPath, moduleSource, "utf8");
  console.log(`Generated ${outputPath} with ${tasks.length} tasks`);
}

main();
