||| This module is auto-generated by scripts/generate-board.js
module BoardData

import TaskTypes

public export
board : TaskBoard
board =
  MkBoard
    [     MkTask 1 "Write documentation" Todo
    ,     MkTask 2 "Implement domain logic" InProgress
    ,     MkTask 3 "Add coverage tooling" Todo
    ]
